KHS-62 Fixed Thing-State ManyToMany
KNITS-OS/KN-Hypersense-Api pull request #13
Opened 2021-05-15 20:06 UTC by dmarinen

2021-05-15 23:02 UTC, ExiledRain approved these changes

2021-05-15 23:03 UTC, ExiledRain approved these changes

2021-05-15 23:10 UTC, ExiledRain requested changes

2021-05-15 23:10 UTC, ExiledRain commented on src/main/java/com/knits/coreplatform/web/rest/DeviceResource.java
> -    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.COMPANY_ADMIN + "\")")
Is it ok that you lose all the changes?

2021-05-15 23:10 UTC, ExiledRain commented on src/main/java/com/knits/coreplatform/web/rest/DeviceResource.java
> -    @PreAuthorize("hasAnyAuthority(\"" + AuthoritiesConstants.COMPANY_ADMIN + "\",\"" + AuthoritiesConstants.COMPANY_ADMIN + "\")")
Another lost update

2021-05-15 23:10 UTC, ExiledRain commented on src/main/java/com/knits/coreplatform/web/rest/DeviceResource.java
> -    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.COMPANY_ADMIN + "\")")
Lost authority

2021-05-15 23:10 UTC, ExiledRain commented on src/main/java/com/knits/coreplatform/web/rest/DeviceResource.java
> -    @PreAuthorize("hasAnyAuthority(\"" + AuthoritiesConstants.COMPANY_ADMIN + "\",\"" + AuthoritiesConstants.COMPANY_ADMIN + "\")")
Lost authority

2021-05-15 23:10 UTC, ExiledRain commented on src/main/java/com/knits/coreplatform/web/rest/LocationResource.java
> -    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.COMPANY_ADMIN + "\")")
Lost authority

2021-05-16 08:23 UTC, dmarinen commented
Just checked the code directly on GitHub and mentioned  problems are not there.

2021-05-16 09:02 UTC, closed without merging